### ISSUE TITLE
Seems to fail on isPlainHostName entries

### ISSUE THREAD

**Issue by sleetish** [Arcath/pac-file-tester#2]
evalmachine.<anonymous>:367
        if (isPlainHostName(host))
        ^

ReferenceError: isPlainHostName is not defined
    at FindProxyForURL (evalmachine.<anonymous>:367:2)
    at evalmachine.<anonymous>:2554:11
    at Script.runInContext (vm.js:107:20)
    at Object.runPAC (C:\Users\x\AppData\Roaming\npm\node_modules\pac-file-tester\lib\pac-file-tester.js:91:12)
    at QueryReqWrap.callback (C:\Users\x\AppData\Roaming\npm\node_modules\pac-file-tester\lib\pac-file-tester.js:31:26)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:197:10)

**Comment by Arcath** [comment]
Sorry about that I'd missed providing that function to the VM.

I've released 0.0.7 that contains this fix.
